Шайхисламов Дамир
urfu-2017/webdev-task-2 pull request #20
Opened 2018-03-14 09:54 UTC by Damirikys

2018-03-14 09:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-14 09:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-14 10:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-15 07:33 UTC, dimastark commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Наверно это не должно было попасть в git?

2018-03-15 07:33 UTC, dimastark commented on .eslintrc
> +    "rules": {
Не читерить) Таким образом можно и вообще линтинг отключить.

2018-03-15 07:33 UTC, dimastark commented on README.md
> +##### Каждый запрос должен содержать в headers ключ Authorization с токеном
👍

2018-03-15 07:33 UTC, dimastark commented on README.md
> +  "type": "2",
А для чего `type`?

2018-03-15 07:33 UTC, dimastark commented on app.js
> +app.use(errorMiddleware).listen(config.PORT)
Давай в разные строчки. Просто тогда не понятно, почему не все объединено, а только эти две строки

2018-03-15 07:33 UTC, dimastark commented on app.js
> +const app = express()
Ты ради этого что ли сделал `"no-cap": 0`? Можно же импортить `Express`, а не `express`

2018-03-15 07:33 UTC, dimastark commented on controllers/location/all.js
> +    if (typeof results === 'object') {
А для чего эта проверка? Потому что
```
typeof [] === 'object'
```

2018-03-15 07:33 UTC, dimastark commented on controllers/location/all.js
> +    if (typeof results === 'object') {
Если хотел проверить, что это не массив, то есть метод `Array.isArray`. Но я даже в этой проверке смысле не вижу, потому что `Array.from` все равно для "не массивов" вернет пустой массив

2018-03-15 07:33 UTC, dimastark commented on controllers/location/clear.js
> +import { OK } from 'http-status-codes/index'
`import { OK } from 'http-status-codes'`?

2018-03-15 07:33 UTC, dimastark commented on controllers/location/create.js
> +import { CREATED } from 'http-status-codes/index'
`import { CREATED } from 'http-status-codes'`?

2018-03-15 07:33 UTC, dimastark commented on controllers/location/create.js
> +        location = DB.create(Location.NAME,
Двойной вызов `create` у двух разных штук выглядит очень странно

2018-03-15 07:33 UTC, dimastark commented on controllers/location/create.js
> +        DB.delete(location)
Это точно необходимо делать? В каком случае может остаться мусор?

2018-03-15 07:33 UTC, dimastark commented on controllers/location/get.js
> +import { NOT_FOUND } from 'http-status-codes/index'
`import { NOT_FOUND } from 'http-status-codes'`?

2018-03-15 07:33 UTC, dimastark commented on controllers/location/remove.js
> +import { NOT_FOUND, OK } from 'http-status-codes/index'
`import { NOT_FOUND, OK } from 'http-status-codes'`?

2018-03-15 07:33 UTC, dimastark commented on controllers/location/swap.js
> +import { BAD_REQUEST, OK } from 'http-status-codes/index'
`import { BAD_REQUEST, OK } from 'http-status-codes'`?

2018-03-15 07:33 UTC, dimastark commented on controllers/location/update.js
> +import { NOT_FOUND } from 'http-status-codes/index'
`import { NOT_FOUND } from 'http-status-codes'`?

2018-03-15 07:33 UTC, dimastark commented on controllers/location/update.js
> +        Object.keys(body)
Можно сделать `Object.entries` и тогда в `mapKeyToValue` не придется обращаться к `data` по ключу

2018-03-15 07:33 UTC, dimastark commented on middlewares/authMiddleware.js
> +const AUTHORIZATION_KEY = 'Authorization'
Ну совсем не вижу смысла в этой переменной

2018-03-15 07:33 UTC, dimastark commented on routes/locations.js
> +router.get('/', all)
Нехватает `Возможность отметить место посещённым или непосещённым` - должно быть отдельной ручкой, которая может только помечать событие посещенным.

Что-то на подобии `POST /:uuid/visit`

2018-03-15 07:33 UTC, dimastark commented
🍅

2018-03-15 11:52 UTC, Damirikys commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@dimastark ну в `.gitignore` я исключил `.idea/`, шо це таке за фокус

2018-03-15 12:03 UTC, Damirikys commented on .eslintrc
> +    "rules": {
@dimastark та нет тут читерства, я ж не в пабг играю
`"semi": 0` - нет смысла везде в конце ставить `;` когда Бабель все равно ставит за тебя
`"new-cap": 0` - `express.Router()` виноват, а ставить комментарий `//eslint-disable-line` в коде не хочу
`"no-case-declarations": 0` - вообще забыл кстати убрать, нигде в коде нет деклараций переменных в `case`
`"newline-per-chained-call": 0` - бесило то что немогу написать в линию `String(..).toLowerCase().includes(query.toLowerCase())`

2018-03-15 12:04 UTC, Damirikys commented on README.md
> +  "type": "2",
глянуть специфику `Locations`:
```
static PLACE_TYPE = {
     0: 'city',
     1: 'country',
     2: 'sight'
}
```

2018-03-15 12:06 UTC, Damirikys commented on app.js
> +app.use(errorMiddleware).listen(config.PORT)
@dimastark так нурм?
```
setupMiddlewares(app)
    .use('/locations', locationsRouter)
    .use(errorMiddleware)
    .listen(config.PORT)
```

2018-03-15 12:08 UTC, Damirikys commented on app.js
> +const app = express()
@dimastark нет, для `express.Router()`

2018-03-15 12:19 UTC, Damirikys commented on controllers/location/all.js
> +    if (typeof results === 'object') {
@dimastark да я ночью могу еще и не так написать) я этот метод уже весь переписал, следующим комитом отправлю

2018-03-15 12:20 UTC, Damirikys commented on controllers/location/clear.js
> +import { OK } from 'http-status-codes/index'
@dimastark ага, автоимпорт зло

2018-03-15 12:23 UTC, Damirikys commented on controllers/location/create.js
> +        location = DB.create(Location.NAME,
@dimastark ну могу обозвать метод и как `Location.from`, просто `create` имхо семантичнее и сразу понятно, что метод - фабрика

2018-03-15 12:24 UTC, Damirikys commented on controllers/location/create.js
> +        DB.delete(location)
@dimastark самому больно было, внутри `DB.create(...)` кидается исключение если сохраняемый объект не соответствует scheme, но почему то (втф мзфк?!) реалм все равно этот объект сохраняет

2018-03-15 12:32 UTC, Damirikys commented on controllers/location/update.js
> +        Object.keys(body)
@dimastark :+1:

2018-03-15 12:34 UTC, Damirikys commented on middlewares/authMiddleware.js
> +const AUTHORIZATION_KEY = 'Authorization'
@dimastark конкретно здесь используется единожды, но вообще говоря такие вещи принято выносить в константы

2018-03-15 12:36 UTC, Damirikys commented on routes/locations.js
> +router.get('/', all)
@dimastark так ТЗ в принципе неоднозначно составлено) возможность отметить место посещенным/непосещенным есть через метод `PATCH /locations/:uuid`, но если очень хочется, то сделаю)

2018-03-15 12:41 UTC, dimastark commented on README.md
> +  "type": "2",
Мне кажется, что это лишнее усложнение) Но если ты так видишь, то ок

2018-03-15 12:41 UTC, dimastark commented on app.js
> +app.use(errorMiddleware).listen(config.PORT)
Ну лучше, чем то, что сейчас

2018-03-15 12:42 UTC, dimastark commented on controllers/location/all.js
> +    if (typeof results === 'object') {
Жиза

2018-03-15 12:43 UTC, dimastark commented on middlewares/authMiddleware.js
> +const AUTHORIZATION_KEY = 'Authorization'
Мне кажется, что в этом файле эта константа не нужна. А во внешний мир она не экспортится. Поэтому мне и кажется, что она не нужна

2018-03-15 12:44 UTC, dimastark commented on routes/locations.js
> +router.get('/', all)
Ну в ТЗ неясно, но имелось в виду именно отдельная ручка

2018-03-15 12:44 UTC, dimastark commented on routes/locations.js
> +router.get('/', all)
Так что да, очень хочется)

2018-03-15 13:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-15 13:35 UTC, Damirikys commented on controllers/location/all.js
> +const transform = (object) => {
@dimastark как тебе такое, Илон Маск? 💃

2018-03-15 14:12 UTC, dimastark commented on .eslintrc
> +    "rules": {
Ну хорошо, по поводу `;` согласен.
По поводу `express.Router` - неужели так страшно поставить `new`, что нужно это правило для всего проекта выключать?

2018-03-15 14:14 UTC, dimastark commented on middlewares/authMiddleware.js
> +    if (req.header('Authorization') !== config.AUTH_TOKEN) {
Можно в таком случае написать
```javascript
if (req.headers.authorization !== config.AUTH_TOKEN)
```

2018-03-15 14:17 UTC, dimastark commented on controllers/location/all.js
> +    const [lim, off] = [limit, offset].map(Number)
Так может написать вот так?
```javascript
[limit, offset] = [limit, offset].map(Number)
```

2018-03-15 14:21 UTC, dimastark commented on controllers/location/all.js
> +const transform = (object) => {
Функциональщиной напахнуло

2018-03-17 10:10 UTC, Damirikys commented on controllers/location/all.js
> +    const [lim, off] = [limit, offset].map(Number)
@dimastark так названия limit и offset уже были задекларированы, тут только если так:
```
const [limit, offset] = [
        req.query.limit || Number.MAX_SAFE_INTEGER,
        req.query.offset || 0
    ].map(Number)
```

2018-03-17 10:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-17 10:24 UTC, dimastark commented on controllers/location/all.js
> +    const [lim, off] = [limit, offset].map(Number)
Так можно же не декларировать
А просто перезаписать, без слова `const`

2018-03-18 15:02 UTC, dimastark requested changes
Немного багов:
1. В случае отсутствующего токена в заголовке Authorization на сервере плюется огромная ошибка. Кажется, что это не нужно (лучше логгировать весь трейсбек, только в случае серверной ошибки)
2. Нужно установить авторизацию только на нужные пути. Потому что сейчас вперед плюется 401, а не 404
3. Делаю POST {} на /locations, получаю `object must be of type 'object', got (undefined)`. Надо либо что-то более осмысленное, либо ничего
4. Очень круто, что порядок и id разделены. Но id уж очень длинный. Может сделать по-короче? Ну или еще лучше если это будет число
5. Можно поломать порядок: создаешь 2 объекта, удаляешь первый объект. Создаешь еще один. Итог: два объекта с order = 2
6. Swap работает немного непредсказуемо. Когда я передаю 1,2 я ожидаю, что поменяются местами объекты с order=1 и c order=2. При повторном запросе, все поменяется обратно. Но оно остается как есть.

В остальном, кажется все работает, а по коду замечаний нет. Почини эти баги и 🍏

2018-03-18 15:02 UTC, dimastark commented on .eslintrc
> +        "new-cap": 0
Давай это правило все таки уберем

2018-03-18 15:02 UTC, dimastark commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Видимо закомитил это раньше. Давай тогда
```
git rm -r --cached .  # Убирает все файлы из git
git add .  # Добавляет все файлы в гит (те, что в .gitignore не добавятся)
git commit -am "Remove ignored files"
```

2018-03-19 13:26 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-19 13:26 UTC, Damirikys commented
@dimastark 
> Очень круто, что порядок и id разделены. Но id уж очень длинный. Может сделать по-короче? Ну или еще лучше если это будет число

https://ru.wikipedia.org/wiki/UUID
> UUID представляет собой 16-байтный (128-битный) номер. 

> Можно поломать порядок: создаешь 2 объекта, удаляешь первый объект. Создаешь еще один. Итог: два объекта с order = 2

![omg-o 1](https://user-images.githubusercontent.com/18160651/37597807-3eac5bd4-2ba2-11e8-8bf8-5d8536df5910.jpeg)

> Swap работает немного непредсказуемо. Когда я передаю 1,2 я ожидаю, что поменяются местами объекты с order=1 и c order=2. При повторном запросе, все поменяется обратно. Но оно остается как есть.

Так при повторном запросе порядок и меняется. Что тут непредсказуемого?

2018-03-19 13:27 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-19 13:32 UTC, dimastark commented on middlewares/authMiddleware.js
> +    if (req.path === '/locations' && req.headers.authorization !== config.AUTH_TOKEN) {
таким образом становится невозможным потом использовать эту мидлвару где-то еще

2018-03-19 13:33 UTC, dimastark commented
> Так при повторном запросе порядок и меняется. Что тут непредсказуемого?

у меня не меняется. Видимо из-за прошлого бага

2018-03-19 13:34 UTC, dimastark commented
https://ru.wikipedia.org/wiki/UUID

это конечно хорошо, но если потом будут страницы с местами, как будет выглядеть урл в браузере?

2018-03-19 14:03 UTC, Damirikys commented
@dimastark так это REST-API же, а не сайт =)

2018-03-19 14:29 UTC, dimastark commented
> @dimastark так это REST-API же, а не сайт =)

Я к тому, что если будет сайт, то биндить тоже надо будет. И тебе придется придумывать slug'и например

2018-03-19 14:30 UTC, dimastark commented on middlewares/authMiddleware.js
> +    if (req.path === '/locations' && req.headers.authorization !== config.AUTH_TOKEN) {
@Damirikys Поправь это и ок

2018-03-20 08:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-20 08:57 UTC, Damirikys commented
```
npm run dev
```

2018-03-20 09:13 UTC, dimastark commented
👍  теперь меня все устраивает

2018-03-20 09:13 UTC, closed without merging