n
urfu-2017/webdev-task-2 pull request #29
Opened 2018-03-14 20:09 UTC by ilearnf

2018-03-14 20:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-22 00:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-22 15:30 UTC, VasiliiKuznecov requested changes

2018-03-22 15:30 UTC, VasiliiKuznecov commented on dataAccess/placesRepository.js
> +        return storage.find(p => p.description.toLowerCase().includes(description.toLowerCase()));
кажется, походящих мест может быть несколько и мы хотим найти их все

2018-03-22 15:30 UTC, VasiliiKuznecov commented on controllers/places.js
> +    res.send(place);
если не нашли место по id, то должны послать 404

2018-03-22 15:30 UTC, VasiliiKuznecov commented on controllers/places.js
> +    if (id) {
кажется, лучше тогда уж разделить на два метода, чем писать if
ведь совершенно разные сценарии поиск по id и по подстроке

2018-03-22 15:30 UTC, VasiliiKuznecov commented on controllers/places.js
> +    const place = new Place({ id: -1,
что за хак с id: -1? разве без него не обойтись?

2018-03-22 15:30 UTC, VasiliiKuznecov commented on dataAccess/placesRepository.js
> +let currentIdx = 0;
currentId?

2018-03-22 15:30 UTC, VasiliiKuznecov commented on dataAccess/placesRepository.js
> +    save(place, order) {
может, лучше два метода: для создания нового и изменения существующего?

2018-03-22 15:30 UTC, VasiliiKuznecov commented on dataAccess/placesRepository.js
> +    setOrder(place, order) {
очень сложночитаемая функция
либо упрости, либо вынеси что-нибудь в функцию/переменную с понятным названием, чтобы было понятно, что происходит

2018-03-22 15:30 UTC, VasiliiKuznecov commented on routes.js
> +        .route('/api/v1/places')
чтобы не писать везде /api/v1, можно описать все пути без префикса в express роутере
а потом использовать его `app.use('/api/v1', apiRouter)`

http://expressjs.com/ru/api.html#router

2018-03-22 15:30 UTC, VasiliiKuznecov commented on routes.js
> +        .get('/api/v1/place/:id?', places.getPlace)
places

2018-03-22 15:30 UTC, VasiliiKuznecov commented on routes.js
> +        .put(places.updatePlace);
обновление места кажется должно происходить по его id
и наверное это должен быть patch, а не put

2018-03-22 15:30 UTC, VasiliiKuznecov commented on routes.js
> +        .post('/api/v1/places', places.createPlace);
это можно перенести выше, сюда:
https://github.com/urfu-2017/webdev-task-2/pull/29/files#diff-d640e5835a6b0c342cf705a06018c2b9R11

2018-03-22 15:30 UTC, VasiliiKuznecov commented on routes.js
> +        .get('/api/v1/place/:id?', places.getPlace)
здесь тоже можно сделать route, раз по одному пути несколько контроллеров на разные методы

2018-04-09 10:49 UTC, ilearnf commented on dataAccess/placesRepository.js
> +        return storage.find(p => p.description.toLowerCase().includes(description.toLowerCase()));
действительно.

2018-04-09 10:56 UTC, ilearnf commented on controllers/places.js
> +    if (id) {
уже впихнул в getAll.

2018-04-09 10:58 UTC, ilearnf commented on controllers/places.js
> +    const place = new Place({ id: -1,
можно и без него. тут -1 явно указывает, что надо сгенерировать id, но можно и не передавать ничего.

2018-04-09 10:59 UTC, ilearnf commented on dataAccess/placesRepository.js
> +let currentIdx = 0;
тут именно индекс, а не айдишник,

2018-04-09 11:00 UTC, ilearnf commented on dataAccess/placesRepository.js
> +let currentIdx = 0;
хорошо, но idx тоже общепринято.

2018-04-09 11:13 UTC, ilearnf commented on dataAccess/placesRepository.js
> +    save(place, order) {
отличие же только в создании id, поэтому нет смысла.

2018-04-09 11:17 UTC, ilearnf commented on routes.js
> +        .put(places.updatePlace);
id берется из тела запроса. по поводу patch - согласен.

2018-04-09 11:26 UTC, ilearnf commented on routes.js
> +        .route('/api/v1/places')
да, удобно.

2018-04-09 11:28 UTC, ilearnf commented on dataAccess/placesRepository.js
> +    setOrder(place, order) {
сделал.

2018-04-09 11:28 UTC, ilearnf commented on routes.js
> +        .get('/api/v1/place/:id?', places.getPlace)
да.

2018-04-09 11:38 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-09 12:15 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-04-09 13:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-04-16 06:41 UTC, closed without merging