Рыженко Роман
urfu-2017/webdev-task-2 pull request #34
Opened 2018-03-14 22:56 UTC by WBDiamond

2018-03-14 22:57 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-14 23:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-03-14 23:05 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-15 06:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-20 11:00 UTC, noveogroup-amorgunov requested changes
Сделано неплохо, но нужно подрефакторить:

- Нужно readme.md обновить (куда кинуть инструкцию по запуску приложения) и описать доступные роуты и их параметры (типо мини-документация)
- Ответ пользователю отсылать с нужным статусом (например 200 - если все ок, 404 - если модель не найдена, 400 - если переданы неверные входные параметры) и вместе со статусом можно отправлять код/сообщение ошибки (которые должны быть вынесены в отдельный файл errorCodes, errorMessages или прям в конфиг)

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/routes.js
> +});
Эту штуку вынести в миддлевар (accessLog), можно помимо типа запроса выводить url и подключать в index.js, если `config.debug === true`
```js
console.log(`${Date.now()}: [${req.method}] ${originalUrl}`)
```

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/routes.js
> +};
немного странно выглядит, давай его не будет оборачивать в otherRouter, либо в мидллевару вынести notFound, либо на уровне apiRoutes сделать

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on config.js
> +  ],
![giphy 2](https://user-images.githubusercontent.com/21186268/37648898-2432794c-2c28-11e8-8924-0e5f30afc351.gif)

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +  console.log(req.body);
удалить все консоль логи дебажные

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +  const record = new Record({ ...req.body, isVisited: false });
isVisited лучше выставлять по умолчанию в false внутри самой модели, это ее ответственность

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +  console.log(record);
del

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +  res.redirect(200, '/api');
Ох, зачем же редирект, просто `res.send(record);` (Отправляем созданное место клиенту)
Вообще гуд практика создать у модели метод `toJSON` из которого возвращаем только публичные/нужные поля без методов, вспомогательных полей и всего остально (для клиента в данном случае)

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +  res.json(Record.searchByDescription(req.query));
почему бы сразу не передать description? вместо целого объекта query

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +};
думаю лучше будет разделить метод обновления сущности и перемещения, много условий и не очевидность как это работает говорит как раз об этом

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +};
Если например объект по id не найден для изменения, то клиенту нужно возвращать соответствующую ошибку со статусом 404 (Not found). Если id не передано - 400 (Bad request) итд

Можешь почитать мой коммент как лучше реализовывать: https://github.com/urfu-2017/webdev-task-2/pull/2/files#r175325813

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +    json.message = `${json.message + Record.updateProperty({ id, property, update })}\n`;
Я так понимаю property название свойства, а update - новое значение? А если нужно несколько параметров обновить? Придется делать несколько запросов - плохо.

Для обновления лучше использовать такой подход:
https://github.com/urfu-2017/webdev-task-2/pull/2/files#r175324611
https://github.com/urfu-2017/webdev-task-2/pull/2/files#r175325813

Перебирать все поля из body (их отправлять) и заменить ими данные в текущей модели, найденную по id

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +  res.json({ message: Record.delete(req.body.id) });
message можно не отправлять в данном случае, а отправлять статус. К примеру, если Record.delete(req.body.id) вернет true, просто отправляем 200 статус, что все ок. А если false - то 404 (что будет означать в контексте апи, что модель не найдена по id)

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +    res.json({ message: Record.deleteAll() });
можно просто отправлять статус 200 без сообщения, клиент таким запрос явно запросил удаление всех сущностей, в ответ он ничего не ждет

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +  }
Нужно реализовать возможность работы сортировки и постраничной навигации вместе

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/models/record.js
> +      this.creationDate = new Date().toLocaleDateString('en-US');
хранить дату лучше всего в типе Date или Number, что удобно для сравнения и поиска. В string форматировать, например в методе toJSON, или вообще не форматировать (если клиенту, фронтенд приложение нужно будет форматировать дату, пусть это там и будет реализовано)

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/models/record.js
> +  }
Прочитай мой коммент про подход с маппингом: https://github.com/urfu-2017/webdev-task-2/pull/7/files#r175671118

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/models/record.js
> +  }
Тоже самое нужно поправить: https://github.com/urfu-2017/webdev-task-2/pull/7/files#r175670331

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/models/record.js
> +  }
Про обновление свойств написал в контроллере, можно сделать намного проще (сообщения которые ты возвращаешь не нужны, нужно вернуть обновленный объект).

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/models/record.js
> +      return `Record ${id} doesn't exist`;
просто вернуть false

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/models/record.js
> +  }
Я не сразу увидел, у тебя тут разные ошибки в одном методе возвращаются, можно добавить модели поле `this.error = null`, и если есть ошибка -> `this.error = errorMessage.recordNotFound` А в контроллере потом смотреть, если `if (record.error)` вернуть ошибку клиенту

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/models/record.js
> +    return 'Wrong move parameter';
Тоже нужно отрефакторить в одном стиле с updateProperty

2018-03-20 11:00 UTC, noveogroup-amorgunov commented on app/models/record.js
> +  static updateProperty({ id, property, update }) {
updateProperty -> update
Давай сделаем чтобы можно было обновить несколько свойств за раз

2018-03-20 11:16 UTC, WBDiamond commented
@noveogroup-amorgunov Раз в третьей задаче тоже скорее всего будут требоваться модификации api, можно будет эти правки (хотя бы частично) сделать в рамках третьей задачи, если время будет поджимать? Просто времени на все вместе мало остается и я не до конца уверен, что успею всё до четверга.

2018-03-20 13:41 UTC, WBDiamond commented on app/controllers/records.js
> +};
@noveogroup-amorgunov я не могу найти, где коммент с рекомендациями по реализации?

2018-03-21 03:06 UTC, noveogroup-amorgunov commented
@WBDiamond частично можно, только напиши список, что не будешь успеешь сделать

2018-03-21 04:19 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +};
@WBDiamond обновил ссылку: https://github.com/urfu-2017/webdev-task-2/pull/2/commits/f993ff97c137ac838724ea1bda69a1d92be1d6da#r175324397

2018-03-21 04:20 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +    json.message = `${json.message + Record.updateProperty({ id, property, update })}\n`;
тоже обновил:
https://github.com/urfu-2017/webdev-task-2/pull/2/commits/f993ff97c137ac838724ea1bda69a1d92be1d6da#r175324611
https://github.com/urfu-2017/webdev-task-2/pull/2/commits/f993ff97c137ac838724ea1bda69a1d92be1d6da#r175325813

2018-03-21 04:28 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +};
![2018-03-21_11-26-48](https://user-images.githubusercontent.com/21186268/37694560-3ac903d6-2cc0-11e8-959d-4f12cf385c3e.png)

2018-03-21 04:28 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +    json.message = `${json.message + Record.updateProperty({ id, property, update })}\n`;
![2018-03-21_11-27-06](https://user-images.githubusercontent.com/21186268/37694576-5c14e668-2cc0-11e8-8d50-0dbfd56fb558.png)
![2018-03-21_11-27-18](https://user-images.githubusercontent.com/21186268/37694577-5c3db520-2cc0-11e8-9fed-857b52adad91.png)

2018-03-21 06:36 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-21 19:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-22 02:00 UTC, noveogroup-amorgunov approved these changes
В общем все выглядит хорошо, ПР закрываю, с условием доделки пунктов в рамках 3-ей задачи

2018-03-22 02:00 UTC, noveogroup-amorgunov commented on Dockerfile
> +CMD node index.js
![giphy 5](https://user-images.githubusercontent.com/21186268/37746775-ba570496-2d73-11e8-9ade-8b124908d2ec.gif)

2018-03-22 02:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +  const record = new Record({ ...req.body });
new Record({req.body}) должно быть достаточно

2018-03-22 02:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +  res.send(record.toJSON());
👍

2018-03-22 02:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +  const id = req.query.id;
const { id } = req.query;

2018-03-22 02:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +  const update = req.body;
data, body (в общем название переменной тут не должно быть глаголом

2018-03-22 02:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +    res.sendStatus(404);
про сообщения от сервера в след задаче сделаешь?

2018-03-22 02:00 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +};
Не хорошо использовать headersSent без явной необходимости:
```js
exports.list = (req, res) => {
   if (req.query.sort) {
     return res.send(Record.getSorted(req.query));
   }
   if (req.query.page) {
     return res.send(Record.getPage(req.query.page));
   }
   res.send(Record.getAll());
};
```
Опять же getSorted  не нужен весь query, достаточно сделать const { sort, sortBy } = query; и передавать только их. И я хочу сортировку вместе с постраничной навигацией :)

2018-03-22 02:01 UTC, noveogroup-amorgunov commented on app/controllers/records.js
> +  res.send(record.toJSON());
вроде бы в express нужно res.json явно прописывать для отправки json-объектов

2018-03-22 02:01 UTC, closed without merging