Евгений Елаков
urfu-2017/webdev-task-2 pull request #40
Opened 2018-03-15 09:30 UTC by Behemothhh

2018-03-15 09:30 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-16 14:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-20 16:01 UTC, Superilya requested changes

2018-03-20 16:01 UTC, Superilya commented on models/user.js
> +module.exports = class User {
Это не модель, это объект User в парадигме ООП. ООП !== MVC. Модель предоставляет интерфейс к какой-то сущности: к базе данных, к http api, или как в вашем случае к массиву в глобале.

2018-03-20 16:01 UTC, Superilya commented on controllers/find.js
> +    res.end(JSON.stringify(storage[query.user].findPlaceByDecription(query.description)));
это ужас у express есть res.json()

2018-03-20 16:01 UTC, Superilya commented on models/user.js
> +module.exports = class User {
хочешь деление по юзерам, пожалуйста, в парадигме mvc это будет выглядеть так. У тебя есть модель User, она в данном случае предоставляет интерфейс для работы с данными пользователя. Тебе надо перенести storage в файл с моделью user, тогда если тебе придётся изменить хранилище, например на базу данных, ты сможешь изменить модель, не трогая контроллеры

2018-03-20 16:02 UTC, Superilya commented
Если есть вопросы, пиши в личку

2018-03-21 06:03 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-21 06:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-03-21 06:30 UTC, Behemothhh commented
и вопрос, как вас в слаке зовут?

2018-03-21 11:52 UTC, Superilya commented
superilya

2018-03-21 12:20 UTC, Superilya approved these changes

2018-03-21 12:20 UTC, closed without merging